server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

#encrypt:
#  key: abcdefghijklmnopqrstuvwxy0123456789

encrypt:
  key-store:
    location: file://${user.home}/keystore/apiEncryptionKey.jks
    password: test1234
    alias: apiencryption

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/HyuckJuneHong/git-local-config

